const NUM_OF_UNO_CARDS = 60;

const ALL_CARD_NAMES = [
  "green-0",
  "green-1",
  "green-2",
  "green-3",
  "green-4",
  "green-5",
  "green-6",
  "green-7",
  "green-8",
  "green-9",
  "green-draw-2",
  "green-skip",
  "green-reverse",
  "draw-4",
  "wild",
  "blue-0",
  "blue-1",
  "blue-2",
  "blue-3",
  "blue-4",
  "blue-5",
  "blue-6",
  "blue-7",
  "blue-8",
  "blue-9",
  "blue-draw-2",
  "blue-skip",
  "blue-reverse",
  // "draw-4",
  // "wild",
  "red-0",
  "red-1",
  "red-2",
  "red-3",
  "red-4",
  "red-5",
  "red-6",
  "red-7",
  "red-8",
  "red-9",
  "red-draw-2",
  "red-skip",
  "red-reverse",
  // "draw-4",
  // "wild",
  "yellow-0",
  "yellow-1",
  "yellow-2",
  "yellow-3",
  "yellow-4",
  "yellow-5",
  "yellow-6",
  "yellow-7",
  "yellow-8",
  "yellow-9",
  "yellow-draw-2",
  "yellow-skip",
  "yellow-reverse"
  // "draw-4",
  // "wild"
];

const COORDINATES = [
  { x: 0, y: 0 },
  { x: 1, y: 0 },
  { x: 2, y: 0 },
  { x: 3, y: 0 },
  { x: 4, y: 0 },
  { x: 5, y: 0 },
  { x: 6, y: 0 },
  { x: 7, y: 0 },
  { x: 8, y: 0 },
  { x: 9, y: 0 },
  { x: 10, y: 0 },
  { x: 11, y: 0 },
  { x: 12, y: 0 },
  { x: 13, y: 0 },
  { x: 14, y: 0 },
  { x: 0, y: 1 },
  { x: 1, y: 1 },
  { x: 2, y: 1 },
  { x: 3, y: 1 },
  { x: 4, y: 1 },
  { x: 5, y: 1 },
  { x: 6, y: 1 },
  { x: 7, y: 1 },
  { x: 8, y: 1 },
  { x: 9, y: 1 },
  { x: 10, y: 1 },
  { x: 11, y: 1 },
  { x: 12, y: 1 },
  { x: 13, y: 1 },
  { x: 14, y: 1 },
  { x: 0, y: 2 },
  { x: 1, y: 2 },
  { x: 2, y: 2 },
  { x: 3, y: 2 },
  { x: 4, y: 2 },
  { x: 5, y: 2 },
  { x: 6, y: 2 },
  { x: 7, y: 2 },
  { x: 8, y: 2 },
  { x: 9, y: 2 },
  { x: 10, y: 2 },
  { x: 11, y: 2 },
  { x: 12, y: 2 },
  { x: 13, y: 2 },
  { x: 14, y: 2 },
  { x: 0, y: 3 },
  { x: 1, y: 3 },
  { x: 2, y: 3 },
  { x: 3, y: 3 },
  { x: 4, y: 3 },
  { x: 5, y: 3 },
  { x: 6, y: 3 },
  { x: 7, y: 3 },
  { x: 8, y: 3 },
  { x: 9, y: 3 },
  { x: 10, y: 3 },
  { x: 11, y: 3 },
  { x: 12, y: 3 },
  { x: 13, y: 3 },
  { x: 14, y: 3 }
];

export { NUM_OF_UNO_CARDS, ALL_CARD_NAMES, COORDINATES };
